[package]
name = "multiqueue2"
version = "0.1.2"
authors = ["Sam Schetterer <samschet@gmail.com>", "Abby <i@abby.md>"]
license = "MIT"
description = "A fast mpmc broadcast queue"
repository = "https://github.com/abbychau/multiqueue"
documentation = "https://docs.rs/multiqueue2"
readme = "Readme.md"
keywords = ["queue", "mpmc", "lockless", "broadcast", "message"]
categories = ['asynchronous', 'concurrency', 'data-structures', 'algorithms']


[dependencies]
crossbeam = "0.4"
futures = "0.1.27"
smallvec = "0.6.9"
parking_lot = "0.8.0"
time = "0.1.42"
atomic_utilities = "0.5.0"
